// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Triddov",
            "url": "https://github.com/Triddov"
        },
        "license": {
            "name": "See repository LICENCE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/refresh": {
            "post": {
                "description": "Принимает refresh-токен, ротирует его и возвращает новую пару access + refresh.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Обновить пару токенов",
                "parameters": [
                    {
                        "description": "Действующий refresh-токен",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RefreshTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/request-code": {
            "post": {
                "description": "Отправляет 6-значный код на email. Действует ограничение по частоте отправки.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Запросить код подтверждения",
                "parameters": [
                    {
                        "description": "Email и идентификатор устройства",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RequestCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RequestCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "post": {
                "description": "Проверяет код, при первом входе регистрирует пользователя с его identity-ключом.\nВозвращает пару токенов (access + refresh).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Подтвердить код и зарегистрироваться/войти",
                "parameters": [
                    {
                        "description": "Код, email, устройство и публичный identity-ключ (base64)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.VerifyCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.VerifyCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/keys/count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает число неизрасходованных one-time prekeys текущего пользователя.\nКлиент использует это для своевременного пополнения пула.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keys"
                ],
                "summary": "Количество оставшихся OTK",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_keys.OTKCountResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/keys/prekeys": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загружает signed prekey и пакет one-time prekeys текущего пользователя.\nВсе ключи передаются в base64. Вызывается при первом запуске и при пополнении пула.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keys"
                ],
                "summary": "Загрузить prekey-бандл",
                "parameters": [
                    {
                        "description": "Identity-ключ, signed prekey и OTK",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_keys.RegisterPrekeysRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/keys/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает prekey-бандл указанного пользователя для установки X3DH-сессии.\nАтомарно расходует один OTK из его пула (если есть). Ключи — в base64.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keys"
                ],
                "summary": "Получить prekey-бандл собеседника",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пользователя (UUID)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_keys.PrekeyBundleResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/messages/ack": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Помечает перечисленные сообщения как доставленные, чтобы они больше не выдавались.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Подтвердить доставку сообщений",
                "parameters": [
                    {
                        "description": "Список ID сообщений",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_message.AckMessagesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/messages/pending": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает до 100 ожидающих сообщений текущего пользователя. ciphertext — в base64.\nПосле сохранения на клиенте их следует подтвердить через /messages/ack.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Получить недоставленные сообщения",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_message.PendingMessagesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/messages/store": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Кладёт E2EE-зашифрованное сообщение в очередь получателя. Сервер не может его расшифровать.\nciphertext передаётся в base64. Используется, когда получатель недоступен по P2P.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Сохранить сообщение для оффлайн-доставки",
                "parameters": [
                    {
                        "description": "Зашифрованное сообщение",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_message.StoreMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_message.StoreMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает пользователя по точному username. Поле found=false, если не найден.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Поиск пользователя по username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username для поиска",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_user.SearchUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/set-username": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Задаёт уникальный username текущего пользователя (3–32 символа). Обязателен после регистрации.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Установить username",
                "parameters": [
                    {
                        "description": "Желаемый username",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.SetUsernameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.SetUsernameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает профиль пользователя вместе с его публичным identity-ключом (base64).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Получить пользователя по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пользователя (UUID)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_user.UserDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_auth.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_auth.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_auth.RequestCodeRequest": {
            "type": "object",
            "required": [
                "device_id",
                "email"
            ],
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "internal_auth.RequestCodeResponse": {
            "type": "object",
            "properties": {
                "retry_after": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_auth.SetUsernameRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "internal_auth.SetUsernameResponse": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_auth.VerifyCodeRequest": {
            "type": "object",
            "required": [
                "code",
                "device_id",
                "email",
                "identity_public_key"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "identity_public_key": {
                    "type": "string"
                }
            }
        },
        "internal_auth.VerifyCodeResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "identity_public_key": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_keys.OTKCountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        },
        "internal_keys.OneTimePrekeyDTO": {
            "type": "object",
            "required": [
                "id",
                "public_key"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "public_key": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "internal_keys.PrekeyBundleResponse": {
            "type": "object",
            "properties": {
                "identity_key": {
                    "type": "string"
                },
                "one_time_prekey": {
                    "type": "string"
                },
                "one_time_prekey_id": {
                    "type": "integer"
                },
                "registration_id": {
                    "type": "integer"
                },
                "signed_prekey": {
                    "type": "string"
                },
                "signed_prekey_id": {
                    "type": "integer"
                },
                "signed_prekey_signature": {
                    "type": "string"
                }
            }
        },
        "internal_keys.RegisterPrekeysRequest": {
            "type": "object",
            "required": [
                "identity_key",
                "registration_id",
                "signed_prekey",
                "signed_prekey_id",
                "signed_prekey_signature"
            ],
            "properties": {
                "identity_key": {
                    "description": "base64",
                    "type": "string"
                },
                "one_time_prekeys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_keys.OneTimePrekeyDTO"
                    }
                },
                "registration_id": {
                    "type": "integer"
                },
                "signed_prekey": {
                    "description": "base64",
                    "type": "string"
                },
                "signed_prekey_id": {
                    "type": "integer"
                },
                "signed_prekey_signature": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "internal_message.AckMessagesRequest": {
            "type": "object",
            "required": [
                "message_ids"
            ],
            "properties": {
                "message_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_message.InitialMessageDTO": {
            "type": "object",
            "properties": {
                "sender_ephemeral_key": {
                    "type": "string"
                },
                "sender_identity_key": {
                    "type": "string"
                }
            }
        },
        "internal_message.PendingMessageDTO": {
            "type": "object",
            "properties": {
                "ciphertext": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message_type": {
                    "type": "integer"
                },
                "sender_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "internal_message.PendingMessagesResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_message.PendingMessageDTO"
                    }
                }
            }
        },
        "internal_message.StoreMessageRequest": {
            "type": "object",
            "required": [
                "ciphertext",
                "message_id",
                "recipient_id",
                "sender_id",
                "timestamp"
            ],
            "properties": {
                "ciphertext": {
                    "type": "string"
                },
                "initial_message": {
                    "$ref": "#/definitions/internal_message.InitialMessageDTO"
                },
                "message_id": {
                    "type": "string"
                },
                "message_type": {
                    "type": "integer"
                },
                "ratchet_index": {
                    "type": "integer"
                },
                "recipient_id": {
                    "type": "string"
                },
                "sender_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "internal_message.StoreMessageResponse": {
            "type": "object",
            "properties": {
                "message_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "will_notify": {
                    "type": "boolean"
                }
            }
        },
        "internal_user.SearchUserResponse": {
            "type": "object",
            "properties": {
                "found": {
                    "type": "boolean"
                },
                "user": {
                    "$ref": "#/definitions/internal_user.UserDTO"
                }
            }
        },
        "internal_user.UserDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "identity_public_key": {
                    "type": "string"
                },
                "last_seen": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT access token. Формат: \"Bearer \u003ctoken\u003e\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "P2P Messenger REST API",
	Description:      "REST API peer-to-peer мессенджера: аутентификация по email-коду,\nуправление профилем, обмен оффлайн-сообщениями (E2EE) и распространение\nSignal Protocol prekey-бандлов. Сервер не может расшифровать сообщения.\nWebRTC-сигналинг вынесен в отдельный сервис и здесь не документируется.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
