upstream p2p_api {
    server 127.0.0.1:8080;
}

upstream p2p_ws {
    server 127.0.0.1:8082;
}

server {
    listen 80;
    server_name triddov.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name triddov.ru;

    include snippets/ssl-params.conf;

    location / {
        # WIP
        # root /var/www/p2p;
        # index index.html;
        # try_files $uri $uri/ =404;
        return 404;
    }

    location = / {
        return 404;
    }

    location /api/ {
        #limit_req zone=p2p_api burst=30 nodelay;
        proxy_pass http://p2p_api;
        include snippets/proxy-params.conf;
    }

    location = /health {
        proxy_pass http://p2p_api;
        include snippets/proxy-params.conf;
        access_log off;
    }

    location /ws {
        proxy_pass          http://p2p_ws;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade    $http_upgrade;
        proxy_set_header    Connection "upgrade";
        include snippets/proxy-params.conf;
        proxy_read_timeout  3600s;
        proxy_send_timeout  3600s;
    }
}
