name: Deploy

on:
  push:
    branches: [main]
    paths:
      - 'p2p-server/**'
  workflow_dispatch:

jobs:
  # test:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v4
  #       - uses: actions/setup-go@v5
  #         with:
  #           go-version: '1.22'
  #       - run: go test ./...

  build:
    # needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { name: p2p-api,       dockerfile: p2p-server/Dockerfile.api }
          - { name: p2p-signaling, dockerfile: p2p-server/Dockerfile.signaling }

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: p2p-server/
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: triddov/${{ matrix.name }}:latest
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy docker-compose and sql-init to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "p2p-server/docker-compose.yaml,p2p-server/sql/init/schema.sql,p2p-server/start_prod.sh"
          target: "~/apps/p2p-backend"
          strip_components: 1

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: cd $HOME/apps/p2p-backend && bash start_prod.sh
