name: Deploy

on:
  push:
    branches: [main]
    paths:
      - 'p2p-server/**'
  workflow_dispatch:

jobs:
  # test:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v4
  #       - uses: actions/setup-go@v5
  #         with:
  #           go-version: '1.22'
  #       - run: go test ./...

  deploy:
    # needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push p2p-api
        uses: docker/build-push-action@v5
        with:
          context: p2p-server/
          file: Dockerfile.api
          platforms: linux/amd64
          push: true
          tags: triddov/p2p-api:latest
          cache-from: type=gha,scope=p2p-api
          cache-to: type=gha,mode=max,scope=p2p-api

      - name: Build & Push p2p-signaling
        uses: docker/build-push-action@v5
        with:
          context: p2p-server/
          file: Dockerfile.signaling
          platforms: linux/amd64
          push: true
          tags: triddov/p2p-signaling:latest
          cache-from: type=gha,scope=p2p-signaling
          cache-to: type=gha,mode=max,scope=p2p-signaling

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.yaml"
          target: "~/apps/p2p-backend"

      - name: Copy sql init
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "p2p-server/sql/init/schema.sql"
          target: "~/apps/p2p-backend/sql/init"    

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: $HOME/apps/p2p-backend/start_script.sh
